WIP: Add i18n translation for global usages
eritislami/evobot pull request #350
Opened 2020-11-21 11:56 UTC by WindSekirun

**OBJECTIVE**
* add code for [i18n-node](https://github.com/mashpie/i18n-node)
* add base translation file (en.json)
* add Korean (ko) translation file (ko.json)

**TODOS**
* [ ] change hard-coded strings into base translation file
* [ ] test all translation is working

2020-11-21 12:45 UTC, wolf-yuan-6115 commented
Hi !
Your pull request is very good!!!
Thank u!

2020-11-21 14:38 UTC, WindSekirun commented
I finished my work of adding translation. Can you review this? @eritislami

2020-11-21 19:44 UTC, eritislami commented
Resolved merge conflicts, if you don't mind can you also add a translation for this line

https://github.com/eritislami/evobot/blob/6546b3750e999183b2b88c985afcb4017f2a2529/include/play.js#L17

2020-11-21 20:22 UTC, WindSekirun commented on include/play.js
> +      return message.client.queue.delete(message.guild.id);
@eritislami Sure! i added translation for 'Leaving the channel...' which related to #351.

But, It seems 'message.client.queue.delete(message.guild.id)' is unreachable due to `return` of L19, 

So, how about modifying it as below?

```
if (!song) {
      setTimeout(function () {
        if (queue.connection.dispatcher && message.guild.me.voice.channel) return;
        queue.channel.leave();
        queue.textChannel.send(i18n.__("play.leaveChannel"));
      }, STAY_TIME * 1000);
      message.client.queue.delete(message.guild.id);
      return queue.textChannel.send(i18n.__("play.queueEnded")).catch(console.error);
    }
```

2020-11-26 04:14 UTC, WindSekirun commented
@eritislami What else do i need to do before merge?

2020-11-26 10:18 UTC, eritislami commented
> @eritislami What else do i need to do before merge?

Nothing it's all good i just need some time

2020-12-04 16:30 UTC, WindSekirun commented
@eritislami I added translation for 'clip', 'clips', 'invite', 'ping' which recently implemented. (and feature is working too.) Can you check? or I need another waiting time?

2020-12-12 12:48 UTC, totolerigolo324 requested changes
I did the translation in French. Interested in me adding it? (I have already made the fr.json file)

2020-12-12 13:21 UTC, WindSekirun commented
@totolerigolo324 I also add translation for 'move' command.

```
"move": {
    "description": "Move songs around in the queue",
    "errorNotQueue": "There is no queue.",
    "usagesReply": "Usage: {prefix}move <Queue Number>",
    "result": "<@{author}> 🚚 moved **{title}** to {index} in the queue."
  },
```

When attaching fr.json, it would be nice if `move` translation was also added.

2020-12-12 13:34 UTC, totolerigolo324 commented
Here is the fr.json: https://gist.github.com/totolerigolo324/235a93b35cadd4806e9125b6f89e0624

2020-12-12 13:47 UTC, WindSekirun commented
@totolerigolo324 Done, by 12d9a73ead6b861db175c32c07125346b5ecb03b.

2020-12-16 09:59 UTC, wolf-yuan-6115 approved these changes

2021-01-21 19:54 UTC, merged

2021-01-21 19:55 UTC, eritislami commented
@WindSekirun & @totolerigolo324 
Thank you for the work you did on this, i finally had some time to merge it all together.