Feature permission
eritislami/evobot pull request #449
Opened 2020-12-05 16:09 UTC by evrardco

Fix for #358,
This pull request adds the possibility to check that users have a certain role before using any command.
Leaving that role to "undefined" falls back to the default free for all behavior.

2020-12-05 16:41 UTC, Perdition0 commented
Can you add command setd?

2020-12-05 16:46 UTC, evrardco commented
> 
> 
> Can you add command setdj?

Wouldn't it be equivalent to add the dj role to someone ? Server owners can natively do that. If not, can you specify what you mean?

2020-12-05 16:53 UTC, Perdition0 commented
What I mean is that each particular server can define an exclusive roleDj
Example:
 /setdj @test
This server becomes its own Role @test

2020-12-05 22:27 UTC, evrardco commented
I think that would require a more complex implementation. Something like a persistent storage that could map roles to servers. It's far from impossible but too complex to simply add it quickly. Maybe for another pull request :)

2020-12-20 14:34 UTC, wolf-yuan-6115 requested changes
So we can create a role called undefined

2020-12-26 10:41 UTC, evrardco commented
Haha Idk why someone would do it but you're right 👍

2020-12-27 02:35 UTC, wolf-yuan-6115 commented
> Haha Idk why someone would do that but you're right 👍 

I think you need to 
```json
{
    "...":"",
    "DJ_ROLE":undefined
}
```

2021-02-14 05:27 UTC, Deepjq commented
Yes plz add DJ role command 
Set DJ role
Remove DJ role

2021-10-06 00:49 UTC, drewburr commented on util/EvobotUtil.js
> +exports.DJ_ROLE = config ? config.DJ_ROLE : process.env.ROLE
We should change `process.env.ROLE` to `process.env.DJ_ROLE` so this config isn't confusing for our Docker users

2021-12-24 02:56 UTC, razeNFR commented
I have a problem with your feature, just the role "undefined" is working, so i have to create a role named "undefined" on my server to be working, if i change the name the server wont start.. I tried to replace "undefined" by "DJ_ROLE" but its not working i have the role "DJ_ROLE" in my server but its not working...

2022-04-25 22:01 UTC, eritislami commented
Closing as this was left behind a long time now, will consider for the future

2022-04-25 22:01 UTC, closed without merging